### ISSUE TITLE
Python/Django?

### ISSUE THREAD

**Issue by nipython** [menshikh-iv/gomoku-rl#4]
Здравствуйте, Иван!
Сразу хочу извиниться, что пишу вам в гитхаб в issue.
Я ищу разработчика с опытом в Python от 2-х лет до 100 лет (а опыт с Python-ом у вас есть, судя по репозиторию :), пониманием веба, опытом в Django, возможностью разговаривать хотя бы на ломаном английском :)
Напишите, пожалуйста, в скайп cv.kulikov@gmail.com (это именно скайп), если это про вас И вам было бы интересно переехать в Минск работать в штате компании на лучших условиях (удаленно мы не можем, увы).
Спасибо

**Comment by menshikh-iv** [comment]
Добрый день @nipython, Django не интересует от слова совсем, как и переезд в Минск, увы, но нет.

P/S Если бы не было моих контактов, я бы понял, почему вы создали issue, но у меня в github профиле написана почта и твиттер, почему было не написать туда? Проверяйте пожалуйста контакты в профиле перед тем, как создавать issue и удачи с поиском питониста :+1:
